services:
  cache:
    image: redis
    ports:
    - 6379:6379
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.local
    volumes:
    - ./frontend:/code
    - /code/node_modules
    - /code/.next
  reverse-proxy:
    depends_on:
    - frontend
    image: caddy:latest
    ports:
    - 3000:3000
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
version: '3.4'
